name: RPGLeveling
version: 0.6
author: rfsantos1996
main: com.jabyftw.rpglv.RPGLeveling
description: RPG like level and unlocking of items
permissions:
   rpglevel.join:
     description: Allow you to join a class.
     default: true
   rpglevel.manager:
     description: Allow you to manage player info.
     default: op
commands:
   class:
     description: Join a class
     permission: rpglevel.join
     usage: Use /class (name/list/exit)
   rpg:
     description: Change player values
     permission: rpglevel.manager
     usage: Use /rpg (kick/level quantity) (player name)