name: RPGLeveling
version: 0.2
author: rfsantos1996
main: com.jabyftw.rpglv.RPGLeveling
description: RPG like level and unlocking of items
permissions:
   rpglevel.join:
     description: Allow you to join a class.
     default: true
commands:
   class:
     description: Join a class
     permission: rpglevel.join
     usage: Use /class (name/list/exit)